Add cert manager migration docs
openshift-service-mesh/sail-operator pull request #179
Opened 2024-12-23 13:41 UTC by nrfox

#### What type of PR is this?
Adds migration docs when using cert-manager.

- [ ] Enhancement / New Feature
- [ ] Bug Fix
- [ ] Refactor
- [ ] Optimization
- [ ] Test
- [ ] Documentation Update

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

Related Issue/PR #

#### Additional information:

2025-01-06 15:41 UTC, FilipB requested changes

2025-01-06 15:41 UTC, FilipB commented on docs/ossm/ossm2-migration/cert-manager/README.md
> +  If you have set the `app.controller.configmapNamespaceSelector` field on your istio-csr deployment to `maistra.io/member-of`, you will need to update this accordingly. If you haven't set this field
Is it possible to have multiple labels defined in `app.controller.configmapNamespaceSelector`? It would be nice to include also some example when you need to keep `maistra.io/member-of` so 2.x is still working while 3.0 namespace would use a different label.

2025-01-06 18:10 UTC, nrfox commented on docs/ossm/ossm2-migration/cert-manager/README.md
> +    --namespace cert-manager \
iirc if you use `istio-system` you have to `--set` more options when installing istio-csr. iirc when I originally wrote the cert-manager docs I was using the [upstream docs](https://cert-manager.io/docs/usage/istio-csr/installation/#5-installing-istio-csr) which has you install istio-csr in the `cert-manager` namespace so that's why it's different.

2025-01-06 18:12 UTC, nrfox commented on docs/ossm/ossm2-migration/cert-manager/README.md
> +  Depending on whether you will use a `RevisionBased` update strategy or an `InPlace` update strategy, your revision name will vary. If using an `InPlace` strategy, your revision name will match your
Ah you're right. Must be some markdown processing error.

2025-01-06 18:24 UTC, nrfox commented on docs/ossm/ossm2-migration/cert-manager/README.md
> +  If you have set the `app.controller.configmapNamespaceSelector` field on your istio-csr deployment to `maistra.io/member-of`, you will need to update this accordingly. If you haven't set this field
>It would be nice to include also some example when you need to keep maistra.io/member-of so 2.x is still working while 3.0 namespace would use a different label.

This is where you need to update the selector **only after** completing the migration and have also added the new injection label to each namespace.

2025-01-07 13:20 UTC, FilipB commented on docs/ossm/ossm2-migration/cert-manager/README.md
> +      --set "app.controller.configmapNamespaceSelector=null"
This was not working for me, the value was unchanged after this. I used `--set "app.controller.configmapNamespaceSelector="`.

2025-01-07 13:36 UTC, FilipB commented
Verified that:
-  `istio-ca-root-cert` is unchanged when updating configmapNamespaceSelector
-  `istio-ca-root-cert` is unchanged when re-created after removal
- communication between sleep 3.0 (after upgrade) <> httpbin 2.6 still works

2025-01-07 20:09 UTC, nrfox commented on docs/ossm/ossm2-migration/cert-manager/README.md
> +      --set "app.controller.configmapNamespaceSelector=null"
I must've copied an array example that used `null`

2025-01-07 20:10 UTC, nrfox commented on docs/ossm/ossm2-migration/cert-manager/README.md
> +  If you have set the `app.controller.configmapNamespaceSelector` field on your istio-csr deployment to `maistra.io/member-of`, you will need to update this accordingly. If you haven't set this field
I'll reword it to make it more clear that you don't always need the injection label.

2025-01-07 20:23 UTC, nrfox commented on docs/ossm/ossm2-migration/cert-manager/README.md
> +    --namespace cert-manager \
The 3.0 documentation uses `cert-manager`: https://docs.redhat.com/en/documentation/red_hat_openshift_service_mesh/3.0.0tp1/html/installing/ossm-cert-manager-assembly#inplace-istio-csr-installation_ossm-cert-manager-assembly so it's a mixed bag. I can update the namespace here to be `istio-system` we'll also need to update the existing 3.0 docs if we want everything to match.

2025-01-08 06:59 UTC, FilipB commented on docs/ossm/ossm2-migration/cert-manager/README.md
> +helm upgrade cert-manager-istio-csr jetstack/cert-manager-istio-csr \
Sorry for complication but since this is 2.6 -> 3.0 migration guide, why not just following the 2.6 OSSM [documentation](https://docs.openshift.com/container-platform/4.16/service_mesh/v2x/ossm-security.html#ossm-cert-manager-installation_ossm-security) as a starting point? That way we will have the same starting point as our customers.

2025-01-08 07:02 UTC, FilipB commented on docs/ossm/ossm2-migration/cert-manager/README.md
> +        address: cert-manager-istio-csr.cert-manager.svc:443
I think this should be `cert-manager-istio-csr.istio-system.svc:443`

2025-01-08 07:03 UTC, FilipB commented on docs/ossm/ossm2-migration/cert-manager/README.md
> +    --namespace cert-manager \
```suggestion
    --namespace istio-system \
```

2025-01-08 07:46 UTC, FilipB commented on docs/ossm/ossm2-migration/cert-manager/README.md
> +      caAddress: cert-manager-istio-csr.cert-manager.svc:443
```suggestion
      caAddress: cert-manager-istio-csr.istio-system.svc:443
```

2025-01-08 07:47 UTC, FilipB commented on docs/ossm/ossm2-migration/cert-manager/README.md
> +        address: cert-manager-istio-csr.cert-manager.svc:443
```suggestion
        address: cert-manager-istio-csr.istio-system.svc:443
```

2025-01-08 07:47 UTC, FilipB commented on docs/ossm/ossm2-migration/cert-manager/README.md
> +        caAddress: cert-manager-istio-csr.cert-manager.svc:443
```suggestion
        caAddress: cert-manager-istio-csr.istio-system.svc:443
```

2025-01-13 15:07 UTC, nrfox commented on docs/ossm/ossm2-migration/cert-manager/README.md
> +helm upgrade cert-manager-istio-csr jetstack/cert-manager-istio-csr \
That makes sense. I was following the [3.0 OSSM docs for cert-manager](https://docs.redhat.com/en/documentation/red_hat_openshift_service_mesh/3.0.0tp1/html/installing/ossm-cert-manager-assembly#ossm-installing-cert-manager_ossm-cert-manager-assembly).

2025-01-14 12:59 UTC, FilipB approved these changes

2025-01-14 16:26 UTC, cam-garrison approved these changes
Added a suggestion to make the order of when to do these steps more clear at the beginning of the doc. Otherwise it LGTM

2025-01-14 16:26 UTC, cam-garrison commented on docs/ossm/ossm2-migration/cert-manager/README.md
> +When migrating from OpenShift Service Mesh 2.6 --> 3.0 while using Cert-Manager you can largely follow the [ClusterWide](TODO) or [MultiTenant](../multi-tenancy/README.md) migration guides with a few
```suggestion
When migrating from OpenShift Service Mesh 2.6 --> 3.0 while using Cert-Manager you can largely follow the [ClusterWide](TODO) or [MultiTenant](../multi-tenancy/README.md) migration guides. This document details a few necessary additional steps to follow before creating your `Istio` resource to ensure your cert manager configuration works with 3.0. 
```

2025-01-15 12:43 UTC, nrfox commented
@FilipB CI keeps failing on different stages. Might need blanket overrides.

2025-01-15 13:24 UTC, FilipB commented
Doc only PR, overriding the tests.

2025-01-15 13:25 UTC, FilipB commented
/override ci/prow/lint ci/prow/e2e-ocp-4-17 ci/prow/e2e-ocp-4-17-arm ci/prow/e2e-ocp-4-18 ci/prow/gencheck ci/prow/integration ci/prow/scorecard ci/prow/unit

2025-01-15 13:34 UTC, merged